yoyo/coaches/urls.py
from django.urls import path
from .views import SearchView, CoachDetail

urlpatterns = [
    path('search/', SearchView.as_view(), name='search'),
    path('id<int:pk>', CoachDetail.as_view(), name='detail'),
]

yoyo/urls.py
from django.urls import re_path, path, include
from django.views.generic import TemplateView
from .core.views import site_index, manifest_view, browser_config_view

app_name = 'yoyo'

urlpatterns = [
    path('', include('yoyo.coaches.urls')),
    path(
        'robots.txt',
        TemplateView.as_view(
            content_type='text/plain', template_name='yoyo/robots.txt'
        )
    ),
    path('manifest.json', manifest_view, name='manifest_json'),
    path('browserconfig.xml', browser_config_view, name='browserconfig_xml'),
    re_path(r'^$', site_index, name='index')
]

# Регистрируем API

apiurlpatterns = [
    # path('', include('')),
]

urlpatterns += [path('api/', include((apiurlpatterns, 'api'), namespace='api'))]

yoyoproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('yoyo.urls', namespace='yoyo')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yoyo/coaches/models.py
from datetime import date
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _


class CoachManager(models.Manager):
    def filter_by_fio(self, fio: list):
        if len(fio) == 3:
            queryset = self.filter(
                last_name__istartswith=fio[0],
                first_name__istartswith=fio[1],
                second_name__istartswith=fio[2]
            )
            if not queryset.exists():
                queryset = self.filter(
                    last_name__istartswith=fio[0],
                    first_name__istartswith=fio[1],
                    second_name__istartswith=fio[2]
                )
                if not queryset.exists():
                    queryset = self.filter(
                        Q(first_name__istartswith=fio[0]) |
                        Q(last_name__istartswith=fio[0]) |
                        Q(second_name__istartswith=fio[0]) |
                        Q(first_name__istartswith=fio[1]) |
                        Q(last_name__istartswith=fio[1]) |
                        Q(second_name__istartswith=fio[1]) |
                        Q(first_name__istartswith=fio[2]) |
                        Q(last_name__istartswith=fio[2]) |
                        Q(second_name__istartswith=fio[2])
                    )
        elif len(fio) == 2:
            queryset = self.filter(last_name__istartswith=fio[0], first_name__istartswith=fio[1])
            if not queryset.exists():
                queryset = self.filter(last_name__istartswith=fio[1], first_name__istartswith=fio[0])
                if not queryset.exists():
                    queryset = self.filter(
                        Q(first_name__istartswith=fio[0]) |
                        Q(last_name__istartswith=fio[0]) |
                        Q(second_name__istartswith=fio[0]) |
                        Q(first_name__istartswith=fio[1]) |
                        Q(last_name__istartswith=fio[1]) |
                        Q(second_name__istartswith=fio[1])
                    )
        else:
            queryset = self.filter(
                Q(first_name__istartswith=fio[0]) |
                Q(last_name__istartswith=fio[0]) |
                Q(second_name__istartswith=fio[0])
            )
        return queryset.order_by('city__alternate_names', 'last_name', 'first_name', 'second_name')


class Coach(models.Model):
    first_name = models.CharField(_('First name'), max_length=60)
    last_name = models.CharField(_('Last name'), max_length=120)
    second_name = models.CharField(_('Second name'), max_length=60, null=True, blank=True)

    born = models.DateField(_('Born date'), null=True, blank=True)
    city = models.ForeignKey(
        'cities_light.City', on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_('City')
    )

    objects = CoachManager()

    class Meta:
        verbose_name = _('Coach')
        verbose_name_plural = _('Coaches')

    def __str__(self):
        return self.full_name

    @property
    def full_name(self) -> str:
        full_name = []
        if self.second_name:
            full_name.append(self.second_name)
        if self.first_name:
            full_name.insert(0, self.first_name)
        if self.last_name:
            full_name.insert(0, self.last_name)
        return ' '.join(full_name)

    @property
    def age(self) -> int:
        today = date.today()
        return today.year - self.born.year - ((today.month, today.day) < (self.born.month, self.born.day))

    @property
    def city_name(self) -> str:
        return self.city.alternate_names.split(';')[-1]

    @property
    def city_name_with_region(self) -> str:
        city_name = self.city_name
        region_name = self.city.region.alternate_names.split(';')[-1]
        if city_name != region_name:
            return f'г. {city_name}, {region_name}'
        return f'г. {city_name}'

yoyo/coaches/models/coach.py
from PIL import Image
from datetime import date
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _
from django.utils.translation import ngettext
from django.urls import reverse
from ..uploader import upload_hero_photo, upload_main_photo

class CoachManager(models.Manager):
    def filter_by_fio(self, fio: list):
        if len(fio) == 3:
            queryset = self.filter(
                last_name__istartswith=fio[0],
                first_name__istartswith=fio[1],
                second_name__istartswith=fio[2]
            )
            if not queryset.exists():
                queryset = self.filter(
                    last_name__istartswith=fio[0],
                    first_name__istartswith=fio[1],
                    second_name__istartswith=fio[2]
                )
                if not queryset.exists():
                    queryset = self.filter(
                        Q(first_name__istartswith=fio[0]) |
                        Q(last_name__istartswith=fio[0]) |
                        Q(second_name__istartswith=fio[0]) |
                        Q(first_name__istartswith=fio[1]) |
                        Q(last_name__istartswith=fio[1]) |
                        Q(second_name__istartswith=fio[1]) |
                        Q(first_name__istartswith=fio[2]) |
                        Q(last_name__istartswith=fio[2]) |
                        Q(second_name__istartswith=fio[2])
                    )
        elif len(fio) == 2:
            queryset = self.filter(last_name__istartswith=fio[0], first_name__istartswith=fio[1])
            if not queryset.exists():
                queryset = self.filter(last_name__istartswith=fio[1], first_name__istartswith=fio[0])
                if not queryset.exists():
                    queryset = self.filter(
                        Q(first_name__istartswith=fio[0]) |
                        Q(last_name__istartswith=fio[0]) |
                        Q(second_name__istartswith=fio[0]) |
                        Q(first_name__istartswith=fio[1]) |
                        Q(last_name__istartswith=fio[1]) |
                        Q(second_name__istartswith=fio[1])
                    )
        else:
            queryset = self.filter(
                Q(first_name__istartswith=fio[0]) |
                Q(last_name__istartswith=fio[0]) |
                Q(second_name__istartswith=fio[0])
            )
        return queryset.order_by('city__alternate_names', 'last_name', 'first_name', 'second_name')


class Coach(models.Model):
    first_name = models.CharField(_('First name'), max_length=60)
    last_name = models.CharField(_('Last name'), max_length=120)
    second_name = models.CharField(_('Second name'), max_length=60, null=True, blank=True)

    born = models.DateField(_('Born date'), null=True, blank=True)
    city = models.ForeignKey(
        'cities_light.City', on_delete=models.SET_NULL, blank=True, null=True, verbose_name=_('City')
    )

    specializations = models.ManyToManyField(
        'yoyo_coaches.Specialization', verbose_name=_('Specialization'), blank=True)
    documents = models.ManyToManyField('yoyo_institutes.Doc', verbose_name=_('Documents'), blank=True)

    hero_photo = models.ImageField(
        _('Big cover photo'),
        help_text=_('This photo does have a 1080x720px'),
        upload_to=upload_hero_photo,
        blank=True,
        null=True
    )
    main_photo = models.ImageField(
        _('Main photo'),
        upload_to=upload_main_photo,
        blank=True,
        null=True
    )

    objects = CoachManager()

    class Meta:
        verbose_name = _('Coach')
        verbose_name_plural = _('Coaches')

    def __str__(self):
        return self.full_name

    @property
    def full_name(self) -> str:
        full_name = []
        if self.second_name:
            full_name.append(self.second_name)
        if self.first_name:
            full_name.insert(0, self.first_name)
        if self.last_name:
            full_name.insert(0, self.last_name)
        return ' '.join(full_name)

    @property
    def age(self) -> int:
        today = date.today()
        return today.year - self.born.year - ((today.month, today.day) < (self.born.month, self.born.day))

    def get_age_display(self) -> str:
        text = ngettext('year', 'years', self.age)
        return '{} {}'.format(self.age, text)

    @property
    def city_name(self) -> str:
        return self.city.alternate_names.split(';')[-1]

    @property
    def city_name_with_region(self) -> str:
        city_name = self.city_name
        region_name = self.city.region.alternate_names.split(';')[-1]
        if city_name != region_name:
            return f'г. {city_name}, {region_name}'
        return f'г. {city_name}'

    def get_absolute_url(self) -> str:
        return reverse('yoyo:detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.hero_photo:
            img = Image.open(self.hero_photo.path)

            if img.width > 1080 or img.height > 720:
                new_image = (1080, 720)
                img.thumbnail(new_image)
                img.save(self.hero_photo.path)

        if self.main_photo:
            img = Image.open(self.main_photo.path)

            if img.width > 128 or img.height > 128:
                new_image = (128, 128)
                img.thumbnail(new_image)
                img.save(self.main_photo.path)

yoyo/coaches/models/specialization.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Specialization(models.Model):
    name = models.CharField(_('Name'), max_length=160)

    class Meta:
        verbose_name = _('Specialization')
        verbose_name_plural = _('Specializations')
        ordering = ['name']

    def __str__(self):
        return self.name

yoyo/core/models.py
from django.db import models

# Create your models here.

yoyo/skills/models.py
from django.db import models

# Create your models here.

yoyo/coaches/forms.py
from django import forms
from .models import Coach


class CoachAdminForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CoachAdminForm, self).__init__(*args, **kwargs)

        self.fields['born'].required = True
        self.fields['city'].required = True

yoyo/coaches/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from .models import Coach
from .utils import generate_qr_code


class SearchView(ListView):
    model = Coach
    paginate_by = 1
    context_object_name = 'coaches'
    template_name = 'yoyo/search.html'
    allow_empty = False

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        if len(self.object_list) == 1:
            coach = self.object_list.first()
            return redirect('yoyo:detail', pk=coach.pk)

        allow_empty = self.get_allow_empty()

        if not allow_empty:
            # When pagination is enabled and object_list is a queryset,
            # it's better to do a cheap query than to load the unpaginated
            # queryset in memory.
            if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                is_empty = not self.object_list.exists()
            else:
                is_empty = not self.object_list
            if is_empty:
                return redirect('yoyo:index')
        context = self.get_context_data()
        return self.render_to_response(context)

    def get_queryset(self) -> list:
        try:
            value = self.request.GET['q']
            if not value:
                return []
            else:
                self.allow_empty = True
        except KeyError:
            return []

        values = value.split(' ', 2)

        # first_name = None
        # last_name = None
        # second_name = None
        #
        # for value in values:
        #     if str(value).endswith(('ан', 'ын', 'ин', 'ских', 'ов', 'ев', 'ской', 'цкой', 'их', 'ых')):
        #         last_name = value
        #     elif str(value).endswith(('ович', 'евич', 'ич', 'овна', 'евна', 'ична', 'инична')):
        #         second_name = value
        #     else:
        #         first_name = value

        # result = self.model.objects.filter_by_fio(
        #     first_name=first_name,
        #     last_name=last_name,
        #     second_name=second_name,
        # )
        result = self.model.objects.filter_by_fio(values)
        return result


class CoachDetail(DetailView):
    model = Coach
    context_object_name = 'coach'
    template_name = 'yoyo/detail.html'

    def get_context_data(self, **kwargs):
        context = {}
        if self.object:
            context['object'] = self.object
            context_object_name = self.get_context_object_name(self.object)
            if context_object_name:
                context[context_object_name] = self.object
            context.update({
                'qr_code': generate_qr_code(self.object, self.request)
            })
        context.update(kwargs)
        return super().get_context_data(**context)

yoyo/core/views.py
from io import BytesIO
from xml.etree import ElementTree
from django.shortcuts import render
from django.http.request import HttpRequest
from django.http.response import JsonResponse, HttpResponse
from django.templatetags.static import static


def site_index(request):
    return render(request, 'yoyo/index.html')


def manifest_view(request: HttpRequest):
    response = {
        'name': 'YoYo.fit',
        'icons': [
            {
                'src': static('yoyo/favicons/android-icon-36x36.png'),
                'size': '36x36',
                'type': 'image/png',
                'density': '0.75',
            },
            {
                'src': static('yoyo/favicons/android-icon-48x48.png'),
                'size': '48x48',
                'type': 'image/png',
                'density': '1.0',
            },
            {
                'src': static('yoyo/favicons/android-icon-72x72.png'),
                'size': '72x72',
                'type': 'image/png',
                'density': '1.5',
            },
            {
                'src': static('yoyo/favicons/android-icon-96x96.png'),
                'size': '96x96',
                'type': 'image/png',
                'density': '2.0',
            },
            {
                'src': static('yoyo/favicons/android-icon-144x144.png'),
                'size': '144x144',
                'type': 'image/png',
                'density': '3.0',
            },
            {
                'src': static('yoyo/favicons/android-icon-192x192.png'),
                'size': '192x192',
                'type': 'image/png',
                'density': '4.0',
            },
        ]
    }

    return JsonResponse(response)


def browser_config_view(request: HttpRequest):
    root = ElementTree.Element('browserconfig')
    app = ElementTree.Element('msapplication')
    tile = ElementTree.Element('tile')
    root.append(app)
    app.append(tile)

    square70x70logo = ElementTree.SubElement(tile, 'square70x70logo')
    square70x70logo.attrib = {
        'src': static('yoyo/favicons/ms-icon-70x70.png')
    }

    square150x150logo = ElementTree.SubElement(tile, 'square150x150logo')
    square150x150logo.attrib = {
        'src': static('yoyo/favicons/ms-icon-150x150.png')
    }

    square310x310logo = ElementTree.SubElement(tile, 'square310x310logo')
    square310x310logo.attrib = {
        'src': static('yoyo/favicons/ms-icon-310x310.png')
    }

    tile_color = ElementTree.SubElement(tile, 'TileColor')
    tile_color.text = '#ffffff'

    tree = ElementTree.ElementTree(root)
    f = BytesIO()
    tree.write(f, encoding='utf-8', xml_declaration=True)

    return HttpResponse(f.getvalue(), content_type='text/xml')

yoyo/institutes/views.py
from django.shortcuts import render

# Create your views here.

yoyo/skills/views.py
from django.shortcuts import render

# Create your views here.

yoyo/users/views.py
from django.shortcuts import render

# Create your views here.

yoyo/templates/yoyo/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" sizes="57x57" href="{% static '/yoyo/favicons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static '/yoyo/favicons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/yoyo/favicons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static '/yoyo/favicons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/yoyo/favicons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static '/yoyo/favicons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static '/yoyo/favicons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static '/yoyo/favicons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/yoyo/favicons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static '/yoyo/favicons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/yoyo/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static '/yoyo/favicons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/yoyo/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% url 'yoyo:manifest_json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static '/yoyo/favicons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <meta property="og:title" content="{% block meta_title %}Найди своего тренера{% endblock %}">
    <meta property="og:site_name" content="YoYo.fit">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:description" content="{% block meta_description %}База квалифицированных тренеров России{% endblock %}">
    <meta property="og:type" content="website">
    <meta property="og:image" content="{% block meta_image %}{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'yoyo/images/og_image_default.png' %}{% endblock %}">

    <link rel="stylesheet" href="{% static 'vendor/uikit/css/uikit.min.css' %}">
    {% block style %}{% endblock %}
    <title>{% spaceless %}{% block title %}{{ settings.site_name }}{% endblock %}{% endspaceless %}</title>
</head>
<body>
{% block content %}{% endblock %}

<script src="{% static 'vendor/uikit/js/uikit.min.js' %}"></script>
<script src="{% static 'vendor/uikit/js/uikit-icons.min.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

yoyo/templates/yoyo/detail.html
{% extends 'yoyo/base.html' %}
{% load static i18n %}

{% block title %}{{ coach.full_name }}{% endblock %}

{% block content %}
    <div class="uk-section uk-flex uk-flex-center uk-flex-middle uk-height-viewport{% if coach.hero_photo %} uk-background-cover{% else %} uk-background-primary{% endif %}"
         {% if coach.hero_photo %}data-src="{{ coach.hero_photo.url }}" uk-img{% endif %}>
        <div class="uk-container uk-text-center">
            <div class="uk-card uk-card-default">
                <div class="uk-card-header">
                    <h3 class="uk-card-title uk-margin-remove-bottom">
                        {{ coach.full_name }}
                    </h3>
                    <p class="uk-text-muted uk-margin-remove">{{ coach.city_name_with_region }}</p>
                    <p class="uk-margin-remove-top">
                        <span class="uk-label uk-label-danger">{{ coach.get_age_display }}</span>
                    </p>
                </div>
                <div class="uk-card-body">
                    <dl class="uk-description-list uk-description-list-divider">
                        <dt>Образование:</dt>
                        <dd>
                            {% for doc in coach.documents.all %}
                                <span class="uk-label uk-text-truncate">{{ doc.institute }}</span>
                            {% endfor %}
                        </dd>
                        <dt>Специализация:</dt>
                        <dd>
                            {% for specialization in coach.specializations.all %}
                                <span class="uk-label uk-text-truncate">{{ specialization.name }}</span>
                            {% endfor %}
                        </dd>
                    </dl>
                </div>
                <div class="uk-card-footer">
                    <a href="#modal-qr-code" class="uk-button uk-button-text" uk-toggle>QR код-ссылка</a>
                </div>
            </div>
            <div class="uk-margin">
                <a href="{% url 'yoyo:index' %}" class="uk-button uk-button-secondary uk-width-1-1">&larr; На
                    главную</a>
            </div>
        </div>
    </div>
    <div id="modal-qr-code" class="uk-flex-top" uk-modal>
        <div class="uk-modal-dialog uk-width-auto uk-margin-auto-vertical">
            <button class="uk-modal-close-outside" type="button" uk-close></button>
            <img src="{{ qr_code }}" alt="" width="400">
        </div>
    </div>
{% endblock %}

yoyo/templates/yoyo/index.html
{% extends 'yoyo/base.html' %}
{% load static %}

{% block title %}Найди своего тренера — База квалифицированных тренеров России{% endblock %}


{% block content %}
    <div class="uk-section uk-section-primary uk-flex uk-flex-center uk-flex-middle uk-height-viewport">
        <div class="container uk-text-center">
            <img src="{% static 'yoyo/images/main_logo.svg' %}" alt="" width="100">
            <h1 class="uk-margin-remove">База квалифицированных тренеров России</h1>
            <form action="{% url 'yoyo:search' %}">
                <label for="id_q" class="uk-form-label uk-text-lead">Найди своего тренера</label>
                <div class="uk-margin">
                    <div class="uk-grid uk-grid-small">
                        <div class="uk-width-expand uk-first-column">
                            <input type="search" name="q" id="id_q" class="uk-input uk-form-large" autofocus required>
                        </div>
                        <div class="uk-width-auto">
                            <button type="submit" class="uk-button uk-button-default uk-form-large uk-width-1-1">
                                Найти &rarr;
                            </button>
                        </div>
                    </div>
                </div>
                <p class="uk-text-small uk-text-left">Введите инициалы тренера. Можно искать по фамилии, имени и/или
                    отчеству.</p>
            </form>
        </div>
        <div class="uk-position-bottom uk-overlay uk-overlay-primary uk-animation-fade uk-visible@l">
            <strong>Внимание!</strong> Наша база находится на стадии наполнения.
            Если вы хотите помочь в наполении напишите нам: <a href="mailto:support@yoyo.fit">support@yoyo.fit</a>
        </div>
    </div>
{% endblock %}

yoyo/templates/yoyo/search.html
{% extends 'yoyo/base.html' %}
{% load i18n %}

{% block title %}
    {% if coaches|length %}
        {% blocktrans count total=coaches|length %}Found {{ total }} coach{% plural %}Found {{ total }} coaches{% endblocktrans %}
    {% else %}
        {% trans 'Coach not found' %}
    {% endif %}
{% endblock %}

{% block content %}
    {% if coaches|length %}
        {% include 'yoyo/includes/search_result.html' %}
    {% else %}
        {% include 'yoyo/includes/not_found.html' %}
    {% endif %}
{% endblock %}